function rl(){
    if (Math.random() < 0.5)
        return "recht";
    return "link";
}

function op() { //other player than current one
    var random = Math.floor(Math.random()*(app.players.length-1))+1
    return app.players[random].name;
}

var stacks = [
    {
        name: "default",
        displayName: function() {
            return text.stacks.default
        },
        cards: [
            function(){ return "Trinke so viele Schlucke wie du willst. Die Person " + rl() + "s von dir trinkt doppelt so viel" },
            function(){ return "Wähle eine Kategorie (z.B. Automarken). Im Uhrzeigersinn sagt jeder etwas, das in diese Kategorie passt. Der erste, der nichts mehr weiß, muss trinken" },
            function(){ return "Alle sagen nacheinander ein Synonym für 'Sex haben'. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Verteile so viele Schlucke, wie volle Gläser auf dem Tisch stehen" },
            function(){ return "Erzähle von einem verrückten Traum" },
            function(){ return "Wähle jemanden, der trinken muss. Du trinkst mit ihm" },
            function(){ return "Alle, die älter als du sind, trinken" },
            function(){ return "Jeder mit einem farbigen Getränk muss trinken" },
            function(){ return "Trinke, wenn du gestern besoffen warst" },
            function(){ return "Du musst mit dem Rücken zu den Anderen sitzen, bis du wieder dran bist" },
            function(){ return "Du spielst Tip-Top gegen " + op() + " (gegenüberstehend abwechselnd einen Fuß vor den anderen, bis ihr euch in der Mitte trefft). Der Verlierer, der keinen Platz mehr findet, trinkt 3 Schlucke" },
            function(){ return "Trinke, wenn du an Geister glaubst" },
            function(){ return "Bis zur nächsten Runden darfst du nicht den Boden berühren" },
            function(){ return "Trinke, wenn du schon einmal auf der Arbeit Sex hattest" },
            function(){ return "Lasst uns gemeinsam anstoßen!" },
            function(){ return "Dinge die " + app.players[0].name + " über alles liebt. Die Person, der nichts mehr einfällt, etwas wiederholt, oder einen Fehler macht, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Trinke so viele Schlucke, wie leere Gläser auf dem Tisch stehen" },
            function(){ return "Du sagst etwas wie <i>\"Derjenige, der als erstes ... machen würde\"</i>. Alle zeigen mit geschlossenen Augen auf die Person, auf die es am ehesten zutrifft. Derjenige mit den meisten Stimmen muss trinken" },
            function(){ return "Spiele einmal Wahrheit oder Pflicht" },
            function(){ return "Verteile einen Schluck, für jede deiner Reisen außerhalb von Europa" },
            function(){ return "Trinke, wenn du schon einmal von der Polizei angehalten wurdest" },
            function(){ return "Alle mit Piercings trinken" },
            function(){ return "Denke an eine Zahl zwischen 1 und 10. Im Uhrzeigersinn versucht jeder die Zahl zu erraten. Der erste, der richtig liegt, wählt jemanden, der trinken muss" },
            function(){ return "Verteile so viele Schlucke, wie du weiße Kleidungsstücke trägst" },
            function(){ return "Die Person, die dir als nächstes in die Augen sieht, trinkt" },
            function(){ return "Jeder, der das gleiche Getränk hat wie du, trinkt" },
            function(){ return "Trinke, wenn du schon einmal Nachts aufgewacht bist und am sprechen/schreien warst" },
            function(){ return "Alle, die größer als du sind, trinken" },
            function(){ return "Erzähle von deinem Lieblingsfilm" },
            function(){ return "Trinke ein Mal für jedes Schmuckstück, das du trägst. (Es zählt alles von Uhren bis zu Piercings)" },
            function(){ return "Ein Spieler deiner Wahl trinkt" },
            function(){ return "Trinke, wenn du schon einmal in der Schule / bei der Arbeit eingeschlafen bist" },
            function(){ return "Bis du wieder dran bist, dürfen alle nur noch mit links trinken" },
            function(){ return "Du hast 2 Runden Zeit aus dem Glas eines Mitspielers zu trinken. Schaffst du es unbemerkt, muss er sein Glas exen" },
            function(){ return "Der Spieler mit dem schwächsten Getränk trinkt" },
            function(){ return "Bis zu deiner nächsten Runde muss jeder trinken, der dir in die Augen schaut" },
            function(){ return "Der Spieler " + rl() + "s von dir holt dir ein Glas Wasser. Bis es leer ist, darfst du nur aus dem Wasserglas trinken" },
            function(){ return "Verteile einen Schluck an einen Spieler, der älter ist als du, wenn möglich. Ansonsten trink sie selbst" },
            function(){ return "Alle trinken" },
            function(){ return "Trinke mit allen, die du heute erst kennengelernt hast" },
            function(){ return "Spiele \"Schere, Stein, Papier\" um 2 Schlucke mit deinem " + rl() + "en Nachbarn" },
            function(){ return "Du musst dein Gegenüber für 2 Runden massieren" },
            function(){ return "Verteile einen Schluck an einen Spieler, der jünger ist als du, wenn möglich. Ansonsten trink sie selbst" },
            function(){ return "Das nächste Mal, wenn ein anderer Spieler trinken muss, trinkst du mit ihm" },
            function(){ return "Alle nennen nacheinander soziale Netzwerke. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Trinke so viel, wie du gewürfelt hast" },
            function(){ return "Alle nennen nacheinander Hunderassen. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Bestimme einen der trinken soll" },
            function(){ return "Alle Spieler müssen dich berühren, der letzte trinkt" },
            function(){ return "Alle Jungs trinken" },
            function(){ return "Alle, die einen String tragen, trinken" },
            function(){ return "Verteile so viele Schlucke, wie du schwarze Kleidungsstücke trägst" },
            function(){ return "Lege deine Arme um deine beiden Nachbarn bis du wieder trinken musst" },
            function(){ return "Die Person mit dem härtesten Alkohol im Glas verteilt an so viele Spieler wie sie will einen Schluck" },
            function(){ return "Du trinkst einmal, dein " + rl() + "er Nachbar 2x, dessen Nachbar 3x, usw. Einmal im Kreis" },
            function(){ return "Der Besitzer dieses Geräts hat die Ehre 2 Schlucke zu verteilen" },
            function(){ return "Alle, die nach Beginn des Spiels dazugestoßen sind, trinken 3" },
            function(){ return "Trinke, wenn du schon einmal im Wasser Sex hattest" },
            function(){ return "Die Person " + rl() + "s von der Person, die diese Regel vorliest, trinkt 2" },
            function(){ return "Bis du das nächste Mal trinken musst, musst du alle Aufgaben der Karten deiner Mitspieler erfüllen" },
            function(){ return "Wenn du das nächste Mal trinken musst, trinken deine Nachbarn mit dir mit" },
            function(){ return "Erzähle von deinem Lieblingsbuch" },
            function(){ return "Trinke, wenn du dir schon einmal die Haare gefärbt hast" },
            function(){ return "Verteile einen Schluck an einen Spieler, der größer ist als du, wenn möglich. Ansonsten trink sie selbst" },
            function(){ return "Wähle etwas, das du magst. Alle Spieler, die es nicht mögen, trinken 2 Schlucke. Wenn niemand trinkt, trinkst du 3 Schlucke" },
            function(){ return "Hebe deine Hände hoch, bis du das nächste Mal trinken musst" },
            function(){ return "Trinke, wenn du ein Appleprodukt besitzt" },
            function(){ return "Wähle jemanden der Wahrheit oder Pflicht spielen muss" },
            function(){ return "Trinke, wenn du seit über einer Woche nicht mehr feiern warst" },
            function(){ return "Der erste Spieler der etwas sagt, trinkt 3" },
            function(){ return "Nennt das Datum, an dem ihr euren ersten Sex hattet, wenn ihr euch erinnert, ansonsten trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Der kleinste Spieler bestimmt jemanden der trinkt" },
            function(){ return "Jeder bietet dir sein Getränk an. Trinke einen Schluck von jemandem. Diese Person darf 3 verteilen" },
            function(){ return "Umarme einen Mitspieler" },
            function(){ return "Mach 20 Sprünge oder trinke 10 Schlucke" },
            function(){ return "Alle, die bei den letzten Wahlen nicht gewählt haben (obwohl sie berechtigt waren), trinken 5 Schlucke" },
            function(){ return "Alle nennen nacheinander Drogennamen. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Jeder, der ein Instrument spielen kann, trinkt" },
            function(){ return "Alle sagen nacheinander ein Synonym für 'Vagina'. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Der jüngste Spieler trinkt" },
            function(){ return "Die letzte Person, die auf Ihr Handy geschaut hat (außer dieses Gerät), muss 3 Mal trinken" },
            function(){ return "Jeder Katzenbesitzer trinkt" },
            function(){ return "Jeder, der schon Mal eine Geldstrafe von der Polizei erhalten hat, trinkt" },
            function(){ return "Wer als letztes getrunken hat, trinkt nochmal" },
            function(){ return "Erzähle wo und wann du den Spieler zu deiner Linken getroffen hast" },
            function(){ return "Mache 5 Kniebeugen" },
            function(){ return "Trinke, wenn du schon einmal besoffen vergessen hast an der richtigen Haltestelle auszusteigen" },
            function(){ return "Tausche den Platz mit dem Spieler " + rl() + "s von dir" },
            function(){ return "Trinke, wenn du schon einmal deinen Penis (oder den deines Partners) gemessen hast" },
            function(){ return "Trinke für alle deine Geschwister" },
            function(){ return "Trinke, wenn du an Gott glaubst" },
            function(){ return "Alle Singles geben jeweils einen Schluck an eine einzige Person ab" },
            function(){ return "Endlich kannst du wieder trinken" },
            function(){ return "Trinke, wenn du schon einmal irgendwo Hausverbot bekommen hast" },
            function(){ return "Der Spieler, der als letztes seine Hand auf den Kopf seines " + rl() + "en Nachbarn legt, muss trinken" },
            function(){ return "Alle nennen nacheinander fremde Währungen. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Trinke, wenn du schon einmal die Unterwäsche deines Partners anprobiert hast" },
            function(){ return "Alle Mädels trinken" },
            function(){ return "Wähle eine Farbe, jeder muss so oft trinken, wie er Kleidungsstücke in diese Farbe hat" },
            function(){ return "Trinke, wenn du diese Woche zu jemandem 'Ich liebe dich' gesagt hast" },
            function(){ return "Trinke, wenn du Corona hattest (Hoffentlich ohne schlimme Folgen)" },
            function(){ return "Spielt einmal \"Ich hab noch nie\" (Sage etwas, das du noch nie gemacht hast. Jeder, der es schon einmal gemacht hat, trinkt 2)" },
            function(){ return "Trinke, wenn du schon einmal bezüglich deines Alters gelogen hast" },
            function(){ return "Mache alles in halber Geschwindigkeit bis du wieder trinken musst" },
            function(){ return "Verteile einen Schluck an einen Spieler, der kleiner ist als du, wenn möglich. Ansonsten trink sie selbst" },
            function(){ return "Das nächste Mal Trinken werden die Schlucke verdoppelt" },
            function(){ return "Vergleiche dich mit deinem " + rl() + "en Nachbarn. Der mit den größeren Händen trinkt" },
            function(){ return "Trinke etwas, das du heute noch nicht getrunken hast" },
            function(){ return "Alle, die ihre Nase mit ihrer Zunge berühren können, verteilen 3 Schlucke" },
            function(){ return "Der Spieler mit dem leersten Glas trinkt" },
            function(){ return "Jeder Fischbesitzer trinkt" },
            function(){ return "Wer von dir und " + op() + " die hellere Unterwäscheträgt, trinkt 2 Schlucke" },
            function(){ return "Alle nennen nacheinander Teile eines Computers. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Jeder mit einem farbigen Getränk muss trinken" },
            function(){ return "Schließe bis zum nächsten Mal Trinken deine Augen" },
            function(){ return "Alle, die gebräunter als du sind, trinken" },
            function(){ return "Wähle etwas, das du nicht magst. Alle Spieler, die es mögen, trinken 2 Schlucke. Wenn niemand trinkt, trinkst du 3 Schlucke" },
            function(){ return "Trinke, wenn du etwas handwerkliches arbeitest" },
            function(){ return "Jeder sagt, welche Serien er gerade guckt. Alle trinken sie für jede Serie, die auch jemand anderes sieht, einen Schluck" },
            function(){ return "Du musst für eine Runde immer einen Schluck trinken bevor du redest" },
            function(){ return "Alle nennen nacheinander Sternzeichen. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Alle Raucher trinken 2" },
            function(){ return "Wenn das nächste Mal jemand trinken muss, musst du auch trinken und schneller sein. Schaffst du es einmal, darfst du aufhören" },
            function(){ return "Wenn du Limo oder Saft in deinem Getränk hast, trinke 2 Mal" },
            function(){ return "Alle Männer mit Glatze oder Frauen mit kurzen Haaren trinken" },
            function(){ return "Alle sagen nacheinander ein Synonym für 'masturbieren'. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Verteile so viele Schlucke, wie Spieler anwesend sind" },
            function(){ return "Alle, die eine Zigarettenschachtel bei sich haben, trinken so viele Schlucke, wie sie Kippen haben (maximal 7)" },
            function(){ return "Mach ein Selfie mit der Person zu deiner Rechten" },
            function(){ return "Alle, die jünger als du sind, trinken" },
            function(){ return "Schließe deine Augen. Die Anderen wählen stumm einen Gegenstand, der dir in die Hand gelegt wird. Wenn du errätst was es ist, trinken die Anderen. Sonst trinkst du" },
            function(){ return "Trinke, wenn du schon einmal Kondome mit Geschmack benutzt hast" },
            function(){ return "Alle sagen nacheinander ein Synonym für 'Prostituierte'. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Erzähle von deiner größten Angst" },
            function(){ return "Alle, die kleiner als du sind, trinken" },
            function(){ return "Wenn dein Geburtstag an einem geraden Datum ist, trinke" },
            function(){ return "Du hast 5 Minuten, um dein Glas auszutrinken" },
            function(){ return "Alle Spieler mit Bart trinken" },
            function(){ return "Stelle eine Regel auf , die für einen anderen Spieler gilt" },
            function(){ return "Trinke, wenn du nicht an Gott glaubst" },
            function(){ return "Die Person, die zuletzt ein soziales Netzwerk gecheckt hat, trinkt 2" },
            function(){ return "Der Spieler mit dem längsten Namen bestimmt jemanden, der trinkt" },
            function(){ return "Verteile 3 Schlucke an eine Person, oder trink selbst 1" },
            function(){ return "Alle sagen nacheinander ein Synonym für 'betrunken sein'. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Der letzte Spieler, der geraucht hat, muss trinken" },
            function(){ return "Alle sagen nacheinander ein Synonym für 'Anus'. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Die nächste Person, die den Raum verlassen will, muss zuerst austrinken" },
            function(){ return "Alle halten den Atem an und blasen ihre Wangen auf. Wer als erstes einatmet, muss trinken" },
            function(){ return "Endlich kannst DU trinken" },
            function(){ return "Alle Jungfrauen trinken" },
            function(){ return "Alle wählen den nüchternsten Spieler, dieser muss exen" },
            function(){ return "Trinke, wenn du Geschwister hast" },
            function(){ return "Du trinkst doppelt für eine Runde" },
            function(){ return "Alle Spieler deren Namen einen Buchstaben enthält, der auch in deinem Namen vorkommt, müssen trinken" },
            function(){ return "Das nächste Mal, wenn ein Spieler für eine Aufgabe ausgesucht werden soll, bist du es automatisch" },
            function(){ return "Erstelle eine Regel, jede Verletzung dieser wird mit einem Schluck bestraft" },
            function(){ return "Verteile so viele Schlucke wie die Anzahl deiner Vornamen" },
            function(){ return "Der Spieler mit dem leersten Glas trinkt es aus" },
            function(){ return "Trinke, wenn du schon einmal auf einem Plumpsklo warst" },
            function(){ return "Trinke, wenn du heute schon auf Instagram warst" },
            function(){ return "Trinke für jeden Buchstaben deines Namens (" + app.players[0].name.length + ")" },
            function(){ return "5 Schlucke für die letzte Person, die angekommen ist, oder einen Schluck für jeden" },
            function(){ return "Alle, die keine Uhr tragen, trinken" },
            function(){ return "Wenn du gerade etwas auf dem Kopf trägst, trinke" },
            function(){ return "Jeder Spieler, der weniger als du wiegt, trinkt" },
            function(){ return "Wer es zuerst schafft dieses Gerät zum Klingeln zu bringen (z.B. durch einen Anruf) verteilt 3" },
            function(){ return "Der erste und letzte Spieler spielen \"Schere, Stein, Papier\" um 3 Schlucke" },
            function(){ return "Verteile 3 Schlucke, wenn du eine bevorzugte politische Partei hast. Trinke 5, wenn deren Name mit N oder A beginnt" },
            function(){ return "Verteile 3 Schlucke, wenn du morgen arbeiten musst" },
            function(){ return "Jeder Hamsterbesitzer trinkt" },
            function(){ return "Alle Singles trinken" },
            function(){ return "Alle, die nüchterner als du sind, trinken" },
            function(){ return "Die Nächste Person, die trinken muss, verteilt 2 Schlucke" },
            function(){ return "Du und " + op() + " trinken und machen zusammen ein Foto" },
            function(){ return "Trinke, wenn du du das vorliest" },
            function(){ return "Verteile so viele Schlucke, wie du einhändige Liegestützen machen kannst" },
            function(){ return "Bewege dich nicht, bis du das nächste Mal trinken musst" },
            function(){ return "Du und der Spieler " + rl() + "s trinken und machen zusammen ein Foto" },
            function(){ return "Dein " + rl() + "er Nachbar ist nun dein Sklave und muss dich bedienen. Er kann sich befreien, indem er eine Aufgabe für dich erledigt" },
            function(){ return "Wer als letztes auf der Toilette war, trinkt" },
            function(){ return "Nenne 3 Vornamen. Wenn einer davon ein Zweitname eines Spielers ist, verteile 3 Schlucke, ansonsten trink sie selbst" },
            function(){ return "Bis zum Ende des Spiels darf niemand eine Zigarette rauchen. Alle, die dagegen verstoßen, müssen ihr Glas auf ex trinken" },
            function(){ return "Trinke 2 Mal, wenn es noch vor Mitternacht ist" },
            function(){ return "Verteile so viele Schlucke wie du Spitznamen in deiner Kindheit hattest" },
            function(){ return "Trinke, wenn du schon einmal dein Handy verloren hast" },
            function(){ return "Ihr seid zu nüchtern! Jeder trinkt 3 Mal" },
            function(){ return "Die Spieler links und rechts von dir müssen gleich viel in ihren Gläsern haben. Derjenige mit mehr im Glas, trinkt bis er genauso viel im Glas hat wie der Andere" },
            function(){ return "Glückwunsch, du darfst trinken!" },
            function(){ return "Alle nennen nacheinander Pizzanamen. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Alle Studenten müssen trinken" },
            function(){ return "Die erste Person, die ein Gummi rausholt, trinkt 5 Schlucke" },
            function(){ return "Trinke 5 Schlucke, wenn du schon einmal betrunken Auto gefahren bist" },
            function(){ return "Was ist dein Traumberuf?" },
            function(){ return "Trinke, wenn du häufig nackt schläfst" },
            function(){ return "Wähle ein Objekt im Raum. Derjenige, der es zuletzt berührt, trinkt" },
            function(){ return "Du sagst ein kompliziertes Wort. Wenn es die Person " + rl() + "s von dir nicht erklären kann, trinkt sie. Sonst trinkst du" },
            function(){ return "Du kannst einmalig eine Aufgabe, die für dich bestimmt ist, ablehnen oder sie von einem anderen Mitspieler erledigen lassen" },
            function(){ return "Trinke, wenn du die längste Studien-/Ausbildungszeit hast" },
            function(){ return "Du und die Person, die du hier am längsten kennst, trinken" },
            function(){ return "Trinke mit deinen Nachbarn so viele schlucke wie du willst" },
            function(){ return "Der letzte Spieler, der das Gerät berührt, muss trinken" },
            function(){ return "Du und dein Gegenüber trinken zusammen 3 Schlucke" },
            function(){ return "Du bist jetzt einmal Daumenmaster. Wenn du irgendwann deinen Daumen an die Tischkante legst, müssen es dir alle gleich tun. Der letzte trinkt 2" },
            function(){ return "Trinke, wenn du ein Mann bist. Sonst trinken alle anderen" },
            function(){ return "Der Gastgeber verteilt 5 Schlucke. Wenn es keinen gibt, verteilst du die Schlucke" },
            function(){ return "Jeder, der dieses Spiel das erste Mal spielt, trinkt" },
            function(){ return "Alle sagen nacheinander ein Synonym für 'Brüste'. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Verteile 3 Schlucke, wenn du schon einmal eine Person des gleichen Geschlechts auf den Mund geküsst hast" },
            function(){ return "Du und dein Gegenüber seid jetzt verheiratet, ihr müsst immer die gleiche Anzahl an Schlucken trinken" },
            function(){ return "Der Spieler, der als letztes etwas von seinem Getränk verschüttet hat, muss trinken" },
            function(){ return "Die letzte Person die aufsteht, muss 3 Schlucke trinken" },
            function(){ return "Verteil so viele Schlucke, wie du heute alkoholische Getränke hattest" },
            function(){ return "Jeder Hundebesitzer trinkt" },
            function(){ return "Trinke, wenn deine Schuhgröße über 45 ist" },
            function(){ return "Alle nennen nacheinander Whiskey-Marken. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Trinke, wenn du schon einmal eine Zahnspange tragen musstest" },
            function(){ return "Schließe deine Augen. Jeder Spieler dessen Getränk du benennen kannst, muss trinken" },
            function(){ return "Trinke durch deine geschlossenen Zähne" },
            function(){ return "Verteile für jedes E in deinem Vornamen einen Schluck und trinke für jedes A einen selbst" },
            function(){ return "Stelle dich mit dem Rücken zu den Anderen. 2 Personen legen nun ihre Hand auf deine Schultern. Wenn du jemanden errätst, muss er trinken. Wenn du keinen errätst, trinkst du" },
            function(){ return "Trinke, wenn du noch bei deinem ersten oder zweiten Getränk bist" },
            function(){ return "Der älteste Spieler trinkt" },
            function(){ return "Der erste Spieler der 'ja' sagt, muss zwei Mal trinken" },
            function(){ return "Alle mit Tattoos trinken" },
            function(){ return "Trinke, wenn du Nagellack trägst" },
            function(){ return "Trinke, wenn du schon einmal drei Tage hintereinander besoffen warst" },
            function(){ return "Trinke, wenn du schon einmal einmal einen der Mitspieler nackt gesehen hast" },
            function(){ return "Du musst dem Spieler " + rl() + "s von dir für 2 Runden massieren" },
            function(){ return "Jeder, der meint nicht betrunken zu sein, trinkt" },
            function(){ return "Der erste Spieler der 'nein' sagt, muss zwei Mal trinken" },
            function(){ return "Du leerst dein Glas bis zur Hälfte" },
            function(){ return "Wenn du jetzt dein Glas leerst, darfst du 5 verteilen" },
            function(){ return "Wenn dein Getränk fast voll ist, trink 2 Schlucke. Wenn nicht, hol dir ein neues" },
            function(){ return "Jeder hebt sein Glas, der letzte muss trinken" },
            function(){ return "Trinke, wenn deine Socken weiß sind" },
            function(){ return "Du und deine beiden Sitznachbarn trinken" },
            function(){ return "Verteile 5 Schlucke, wenn du noch nie geraucht hast" },
            function(){ return "Trinke, wenn du eher 'Moin' statt 'Servus' sagst" },
            function(){ return "Wählt die Person unter euch, die regelmäßig vor allen anderen auf Partys einschläft. Sie verteilt 3 Schlucke" },
            function(){ return "Der Spieler, der als letztes seine Hand auf die Nase seines " + rl() + "en Nachbarn legt, muss trinken" },
            function(){ return "Alle atmen tief ein und sagen ein langgezogenes \"Aaaaahhhh\". Wer zuerst aufhört trinkt" },
            function(){ return "Alle Rechtshänder trinken" },
            function(){ return "Trinke 3 Schlucke wenn deine Füße kleiner sind, als die deines " + rl() + "en Nachbarn, ansonsten verteil sie" },
            function(){ return "Jeder der nüchtern aussieht, trinkt" },
            function(){ return "Trinke, wenn du schon einmal einen Blackout wegen Alkohol hattest" },
            function(){ return "Verteile einen Schluck an einen Spieler, der intelligenter ist als du, wenn möglich. Ansonsten trink sie selbst" },
            function(){ return "Bis zu deiner nächsten Runde musst du jedes Mal lachen, wenn ein anderer Spieler trinkt" },
            function(){ return "Alle nennen nacheinander Namen von Supermärkten. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Bis zu deiner nächsten Runde darf keiner bei seinem Namen genannt werden. Jeder Verstoß wird mit einem Schluck bestraft" },
            function(){ return "Der Spieler mit dem tiefsten Ausschnitt verteilt 3" },
            function(){ return "Jeder, der eine Brille trägt, trinkt" },
            function(){ return "Der aktuelle DJ der Party verteilt 5 Schlucke" },
            function(){ return op() + "wählt ein Kleidungsstück, das du trägst. Wenn du sagen kannst, wo du es gekauft hast, verteile 3 Schlucke. Wenn nicht, trinke sie selbst" },
            function(){ return "Jeder, der im Sommer Geburtstag hat, trinkt" },
            function(){ return "Du und die Person " + rl() + "s neben dir nennen ihren Lieblingsfilm. Die anderen stimmen ab. Derjenige mit dem schlechteren Film muss trinken" },
            function(){ return "Alle nennen nacheinander Cocktailnamen. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Du wählst ein verbotenes Wort. Jeder, der es ab jetzt benutzt, muss trinken" },
            function(){ return "Trinke, wenn du schon einmal einen Striptease gemacht hast" },
            function(){ return "Trinke, wenn du schon einmal eine Unterschrift gefälscht hast" },
            function(){ return "Zeige das letzte Foto, das du auf deinem Handy aufgenommen hast" },
            function(){ return "Trinke, wenn du noch nie Blut gespendet hast" },
            function(){ return "Mache etwas ungewöhnliches, wenn dein " + rl() + "er Nachbar es nicht nachmachen kann trinkt er. Sonst trinkst du" },
            function(){ return "Trinke 3 Schlucke, wenn du nicht alle anderen Spieler nett findest" },
            function(){ return "Der Spieler mit der hellsten Haut muss trinken" },
            function(){ return "Dein Gegenüber und du schauen sich in die Augen. Wer zuerst lacht, trinkt" }
        ]
    },
    {
        name: "crazy",
        displayName: function() {
            return text.stacks.crazy
        },
        cards: [
            function(){ return "Alle, die es nicht schaffen, den oberen Rand ihres Glases komplett in den Mund zu nehmen, trinken 2 Schlucke" },
            function(){ return "Lass dich von beliebig vielen Spielern Ohrfeigen. Verteile 5 Schlucke pro Schlag" },
            function(){ return "Trinke 2 Schlucke, wenn du schon einmal freihändig gepisst hast" },
            function(){ return "Wenn du es schaffst, 5 Minuten lang kein Wort zu sagen, darfst du entscheiden, wer sein Glas austrinken muss" },
            function(){ return "Trinke so viele Schlucke, wie du Schwänze im Mund hattest" },
            function(){ return "Jedes Mal, wenn jemand trinken muss, geben alle ihr Glas an den linken Nachbarn weiter. Aufgehört wird, wenn jeder wieder sein eigenes Glas hat" },
            function(){ return "Trinke ohne deine Hände zu benutzen" },
            function(){ return "Du musst gleichzeitig aus deinem, und dem Glas vom Spieler " + rl() + "s von dir trinken" },
            function(){ return "Lecke den Unterarm deines " + rl() + "en Nachbarns" },
            function(){ return "Mache 10 Liegestütze. Trinke für jede, die du nicht schaffst" },
            function(){ return "Zeige deine Intimbehaarung oder trink 5 Schlucke" },
            function(){ return "Trinke 3 Schlucke, wenn du schon einmal laut in der Öffentlichkeit gefurzt hast" },
            function(){ return "Die erste Person, die ihren Hintern zeigt, verteilt 7 Schlucke" },
            function(){ return "Laufe durch den Raum wie ein sterbendes Hühnchen" },
            function(){ return "Kaue an den Haaren eines Mitspielers" },
            function(){ return "Lecke die Wange deines " + rl() + "en Nachbarns" },
            function(){ return "Der letzte der \"Penis\" ruft, trinkt 3" },
            function(){ return "Der Reihe nach muss jeder rülpsen wer nicht will/kann trinkt 5" },
            function(){ return "Balanciere dein Glas auf dem Hintern der Person " + rl() + "s von dir. Versuche aus dem Glas zu trinken, ohne deine Hände zu benutzen" },
            function(){ return "Stell dich auf ein Bein und trinke" },
            function(){ return op() + " zählt bis 42. Verteile so viele Schlucke, wie du es schaffst dich in der Zeit um dich selbst zu drehen" },
            function(){ return "Schreie während du sprichst, bis du das nächste Mal trinken musst" },
            function(){ return "Das Mädchen (oder der Junge) mit der größten Oberweite trinkt 3 Schlucke" },
            function(){ return "Kratze den Arsch deines " + rl() + "en Nachbarns" },
            function(){ return "Tu so als würdest du kacken oder trinke 3" },
            function(){ return "Lege dich auf den Boden, bis du das nächste Mal trinken musst" },
            function(){ return "Hebe den Spieler " + rl() + "s von dir hoch. Wenn du es nicht schaffst, musst du trinken" },
            function(){ return "Trinke so oft wie du diese Woche gekackt hast" },
            function(){ return "Schütte ein bisschen deines Getränks auf deinen Kopf" },
            function(){ return "Erzähle von dem komischsten Porno, den du jemals gesehen hast" },
            function(){ return "Wer zuletzt deine Füße berührt, trinkt" },
            function(){ return "Jedes Mal wenn jemand furzt, musst du trinken" },
            function(){ return "Such einen Gegner zum Armdrücken aus, der Verlierer trinkt 3 Schlucke " },
            function(){ return "Wenn du dich nach dem Kacken schon mal mit Pflanzen abgewischt hast, trink 2 Schlucke" },
            function(){ return "Gib deinem " + rl() + "en Nachbarn einen Kuss auf den hintern oder trinke 5" },
            function(){ return "Rieche an den Achselhöhlen von " + op() + " oder trink 5 Schlucke" },
            function(){ return "Trinke 5 Schlucke, wenn du Alkohol nicht verträgst" },
            function(){ return "Schließe deine Augen, halte dir die Nase zu und öffne deinen Mund. Die anderen Spieler dürfen jetzt jedes Getränk in den Mund gießen, das sie wollen" },
            function(){ return "Alle stimmen ab. Entweder trinkt jeder ab jetzt aus deinem Glas, oder du trinkst so oft, wie andere mitspielen" },
            function(){ return "Wer als erstes ein Bild von sich mit einer Zahnlücke zeigt, verteilt 3 Schlucke" },
            function(){ return "Die erste Person, die laut furzt, verteilt 10 Schlucke" },
            function(){ return "Die erste Person, die rülpst, trinkt 3 Schlucke" },
            function(){ return "Für jeden Schluck, den du aus dem Glas anderer Spieler trinkst, muss der Besitzer 3 trinken" },
            function(){ return "Hol sich einen Popel aus der Nase oder trink 3 Schlucke" },
            function(){ return "Alle kippen ein bisschen aus ihrem Glas in deins. Du kannst davor optional austrinken" },
            function(){ return "Lecke den Boden oder trink 5 Schlucke" },
            function(){ return "Was wurde dir als letztes in deinen Arsch gesteckt? Antworte und trinke" },
            function(){ return "Der erste der rülpst, verteilt 3" },
            function(){ return "Reibe deinen Kopf am Hintern von " + op() + " oder trink 5 Schlucke" },
            function(){ return "Lass dir ein wenig eines fremden Getränks in deine Hand schütten und trinke es" },
            function(){ return "Verteile 3 Schlucke, wenn du es schaffst an deinem großen Zeh zu lutschen" },
            function(){ return "Iss ein Blatt Toilettenpapier oder trinke 5 Schlucke" },
            function(){ return "Wähle " + Math.ceil(app.players.length/2) + " Spieler die aus deinem Glas trinken müssen" },
            function(){ return "Hole ein extra Glas. Du und deine Nachbarn füllen etwas von ihren Getränken hinein. Stimmt danach in der Gruppe ab, wer es austrinken muss" },
            function(){ return "Trinke, wenn du zu Hause die Toilettentür offen lässt" },
            function(){ return "Lege dich auf den Rücken und trinke" },
            function(){ return "Spucke in dein Getränk oder trinke es aus" },
            function(){ return "Erzähl uns von deinem letzten Aufenthalt im Krankenhaus. Beschreibe es möglichst blutig" },
            function(){ return "Du musst aus deinem Glas trinken, während du es drehst. Du darfst erst aufhören, wenn du es einmal um 360 Grad gedreht hast" }
        ]
    },
    {
        name: "hot",
        displayName: function() {
            return text.stacks.hot
        },
        cards: [
            function(){ return "Dafür oder dagegen, sich den Anus lecken zu lassen? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Dein linker Nachbar wählt die Person und dein rechter Nachbar eine intime Stelle, die du mit deiner Wange streichelst" },
            function(){ return "Wer hat den heißesten BH? Die Jungs bilden die Jury, die Gewinnerin verteilt 3" },
            function(){ return "Du tauscht mit dem dir am nächsten sitzenden Spieler des anderen Geschlechts ein Kleidungsstück" },
            function(){ return "Trinke, wenn du schon einmal Sex im Wald hattest" },
            function(){ return "Die Person, die am häufigsten an einem Tag masturbiert hat, verteilt 3 Schlucke" },
            function(){ return "Lieber zu dritt oder mit 10 Personen auf einmal Sex haben? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Lieber dich oder " + op() + " küssen? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Gib " + op() + " etwas Essbares von Mund zu Mund weiter" },
            function(){ return "Trinke, wenn jemand schon einmal Geld ausgegeben hat, um mit dir zu schlafen (Drinks, etc…)" },
            function(){ return "Zeig deinen Hintern oder trink 5 Schlucke" },
            function(){ return "Dafür oder dagegen, den Anus des Partners zu lecken? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Verteile 3 Schlucke an die Person, mit der " + op() + " am ehesten Sex haben würde" },
            function(){ return "Lieber oral oder vaginal? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Kuschel mit deinem rechten Nachbarn" },
            function(){ return "Trinke, wenn du schon einmal masturbiert hast, während dich jemand geleckt hat" },
            function(){ return "Die Person, die zuerst ein Kleidungsstück ausgezogen hat, verteilt 5 Schlucke (Socken etc. zählen nicht)" },
            function(){ return "Umarme einen Mitspieler" },
            function(){ return "Trinke, wenn du schon einmal einmal einen der Mitspieler nackt gesehen hast" },
            function(){ return "Schließe deine Augen. Die Anderen wählen stumm eine Person. Du darfst sie nur am Bauch abtasten. Wenn du errätst wer es ist, trinkt die Person. Sonst trinkst du" },
            function(){ return "Küsse den Oberkörper eines Mitspielers" },
            function(){ return "Trinke, wenn du schon einmal masturbiert, um besser schlafen zu können" },
            function(){ return "Alle trinken und ziehen ein Kleidungsstück aus" },
            function(){ return "Wer hat den schönsten Hintern? Die Mädels bilden die Jury, der Gewinner verteilt 3" },
            function(){ return "Gehe auf alle Viere und biege deinen Rücken durch, bis du wieder trinken musst" },
            function(){ return "Lieber Handschellen oder eine Peitsche beim Sex benutzen? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Alle Jungfrauen trinken" },
            function(){ return "Wähle einen Spieler, der in 5 Sekunden den BH einer Mitspielerin mit einer Hand aufbekommen muss. 5 Schlucke, wenn er es nicht schafft" },
            function(){ return "Alle trinken und ziehen ein Kleidungsstück aus" },
            function(){ return "Kneife " + op() + " in die Brust oder er/sie trinkt 5 Schlucke" },
            function(){ return "Streichele den Intimbereich von " + op() + ". 5 Schlucke an euch, wenn sich einer weigert" },
            function(){ return "Trinke, wenn du schon einmal eine Pause beim Sex gemacht hast, um pinkeln zu gehen" },
            function(){ return "Für oder gegen FKK? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Wähle welcher deiner Nachbarn die Hand für eine Runde unter deinem Hintern lassen muss" },
            function(){ return "Soll die Frau beim Sex eher oben oder unten liegen? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Du ziehst " + op() + " ein Kleidungsstück aus" },
            function(){ return "Knabbere am Ohr von " + op() },
            function(){ return "Küsse so viele Spieler wie du willst. Für jeden, den du nicht geküsst hast, musst du einmal trinken" },
            function(){ return "Die anderen wählen eine Person. Versuche dieser Person nun einen Knutschfleck zu machen. Wenn er nach 3 Minuten nicht gut sichtbar ist, musst du exen" },
            function(){ return "Stecke einer Person die Hand in die Hose, während sie ihr Glas austrinkt" },
            function(){ return "Wähle, wer sich ein Kleidungsstück ausziehen muss" },
            function(){ return "Ziehe ein Kleindungsstück aus" },
            function(){ return "Lieber lecken oder fummeln? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Lese die erste Nachricht vor, die angezeigt wird, wenn man 'Schwanz' in die Suchleiste eingibt" },
            function(){ return "Trinke jetzt so viele Gläser leer wie du willst. Der Spieler " + rl() + "s von dir muss ein Kleidungsstück pro Glas ausziehen" },
            function(){ return "Du hälst ab jetzt die Hand von deinem " + rl() + "en Nachbarn bis du wieder trinken musst" },
            function(){ return "Die Frau mit den größten Brüsten bestimmt, welcher Kerl ihr die Brüste leckt, oder sie trinkt 5 Schlucke" },
            function(){ return "Wähle zwei Personen die eine sexuelle Stellung miteinander andeuten" },
            function(){ return "Der Spieler mit dem schönsten Bauch verteilt 3" },
            function(){ return "Trinke, wenn du schon einmal an einem öffentlichen Ort Sex hattest" },
            function(){ return "Lieber einen extrem intelligenten oder extrem gutaussehenden Partner? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Zeigt nacheinander Tattoos. Diejenigen, die keine haben, trinken 3 Schlucke" },
            function(){ return "Lieber im Auto oder auf einem Tisch Sex haben? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Ziehe ein Kleindungsstück aus" },
            function(){ return "Trinke, wenn du schon einmal auf der Arbeit Sex hattest" },
            function(){ return "Trinke, wenn du gerne versaute Dinge im Bett sagst" },
            function(){ return "Lieber einen Penis mit 9cm oder 36cm? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Trinke, wenn du schon einmal einen Dreier hattest" },
            function(){ return "Öffne den Reißverschluss der Hose einer beliebigen Person mit deinen Zähnen" },
            function(){ return "Entweder du gibst deinem " + rl() + "en Nachbarn einen Kuss auf den Mund, oder er/sie trinkt 5 Schlucke" },
            function(){ return "Für eine Runde müssen alle vor jedem Schluck erotisch stöhnen" },
            function(){ return "Lieber F+ oder eine richtige Beziehung? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Trinke, wenn du schon einmal bekifft Sex hattest" },
            function(){ return "Lieber für immer im Stockdunklen oder im Taghellem Sex haben? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Ab jetzt trinkt jeder sobald ein Mädel ihre Brüste zeigt" },
            function(){ return "Versuche in 5 Sekunden den BH einer Mitspielerin mit einer Hand aufzubekommen. 5 Schlucke, wenn du es nicht schaffst" },
            function(){ return "Wähle zwei Personen, die sich erotisch küssen müssen. 7 Schlucke jeweils, wenn sie sich weigern" },
            function(){ return "Lieber 30 mal an einem Tag ficken oder 30 Tage gar keinen Sex haben? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Trinke, wenn du schon einmal beim Sex an eine andere Person gedacht hast" },
            function(){ return "Denke an eine Sex-Toy. Alle versucht es im Uhrzeigersinn zu erraten. Der Erste der es herausfindet darf 3 Schlucke verteilen" },
            function(){ return "Wähle eine Stelle an deinem Körper. Der letzte Spieler, der sie berührt, trinkt 3 Schlucke" },
            function(){ return "Deute eine sexuelle Stellung mit einem anderen Spieler an" },
            function(){ return "Der letzte Spieler, der sich die Hand in die Unterhose steckt, trinkt 3 Schlucke" },
            function(){ return "Alle Mädels ziehen ein Kleidungsstück aus oder trinken 5 Schlucke" },
            function(){ return "Ab jetzt zieht jeder, der ein Schimpfwort sagt, ein Kleidungsstück aus oder trinkt 5 Schlucke" },
            function(){ return "Trinke, wenn du schon einmal die Unterwäsche deines Partners anprobiert hast" },
            function(){ return "Alle Jungs ziehen ein Kleidungsstück aus oder trinken 5 Schlucke" },
            function(){ return "Lieber morgens oder abends Sex? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Lieber untenrum ein wenig Behaarung oder völlig glatt rasiert? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Alle sagen nacheinander ein Sex-Toy. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Wer hat die heißeste Boxershorts? Die Mädels bilden die Jury, der Gewinner verteilt 3" },
            function(){ return "Lecke deinen Finger so erotisch wie möglich" },
            function(){ return "Trinke, wenn du schon einmal Sex in einer Badewanne hattest" },
            function(){ return "Lass dir die Augen verbinden. Zwei Spieler küssen dich wo sie wollen. Wenn du einen errätst, verteilst du 3 Schlucke" },
            function(){ return "Trinke, wenn du häufig nackt schläfst" },
            function(){ return "Ein Dreier mit einer Gleichgeschlechtlichen Person haben möglich oder nicht? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Trinke, wenn du schon einmal deinen Penis (oder den deines Partners) gemessen hast" },
            function(){ return "Nenne etwas sexuelles, das du noch nie gemacht hast. Alle, die es bereits gemacht haben, trinken 3 Schlucke" },
            function(){ return "Du und " + op() + " füßelt für eine Runde" },
            function(){ return "Lieber einen sehr schlanken oder etwas molligen Partner? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Erzähle von etwas Versautem, das du getan hast" },
            function(){ return "Alle sagen nacheinander ein Synonym für Vagina. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Alle anderen nennen nacheinander Orte an denen du Sex hattest. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Dein linker Nachbar beginnt" },
            function(){ return "Massiere den Kopf von " + op() + ", oder trinke 3 Schlucke" },
            function(){ return "Bevorzugst du Anal-, Oral- oder Vaginalsex?" },
            function(){ return "Verteile so viele Schlucke, wie es Titten im Raum gibt" },
            function(){ return "Mädels, ihr verteilt eure Körbchengröße in Schlucken (A = 1, B = 2, etc.)" },
            function(){ return "Der Spieler, der als letztes seine Hand auf die Brust seines " + rl() + "en Nachbarn legt, muss trinken" },
            function(){ return "Wer hat das heißeste Höschen? Die Jungs bilden die Jury, die Gewinnerin verteilt 3" },
            function(){ return "Zeigt nacheinander eure Piercings. Diejenigen, die keine haben, trinken 3 Schlucke" },
            function(){ return "Würdet ihr in einem Porno mitspielen? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Lecke den Bauchnabel eines Spielers deiner Wahl" },
            function(){ return "Schließe deine Augen. Errate nun die Farbe der Unterwäsche deines " + rl() + "en Nachbarn. Trinke wenn du falsch liegst" },
            function(){ return "Zeige deine Intimbehaarung oder trink 5 Schlucke" },
            function(){ return "Dein " + rl() + "er Nachbar muss dir ein Kleidungsstück geben, das du tragen musst" },
            function(){ return "Gib deinem " + rl() + "en Nachbarn etwas Essbares von Mund zu Mund weiter" },
            function(){ return "Lieber Reiter- oder Löffelchen-Stellung? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Lieber am Strand oder auf einer Wiese Sex haben? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Erogene Zonen von " + op() + ", wer nichts mehr weiß oder etwas wiederholt, trinkt. Du beginnst" },
            function(){ return "Wer von dir und " + op() + " die hellere Unterwäscheträgt, trinkt 2 Schlucke" },
            function(){ return "Trinke, wenn du schon einmal Sex in der Dusche hattest" },
            function(){ return "Wer zuletzt in einem Flugzeug geflogen ist, trinkt 3" },
            function(){ return "Lieber viel zu große oder viel zu kleine Brüste? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Trinke, wenn du schon einmal 3 oder mehr Finger in eine andere Person gesteckt hast" },
            function(){ return "Wähle zwei Personen, die sich küssen oder 5 Schlucke trinken müssen" },
            function(){ return "Zeige " + op() + " eine deiner Brustwarzen oder trinke 7 Schlucke" },
            function(){ return "Der Spieler mit dem tiefsten Ausschnitt verteilt 3" },
            function(){ return "Küsse den nächesten Spieler des gleichen Geschlechts " + rl() + "s von dir" },
            function(){ return "Der Spieler, der die meisten Kleidungsstücke trägt trinkt und zieht ein Teil aus" },
            function(){ return "Lese die erste Nachricht vor, die angezeigt wird, wenn man 'Blasen' in die Suchleiste eingibt" },
            function(){ return "Lieber einen sehr schlanken oder etwas molligen Partner? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Trinke, wenn du schon einmal im Wasser Sex hattest" },
            function(){ return "Wähle jemanden, der eine Stelle deines Körpers ablecken muss. 5 Schlucke, wenn die Person sich weigert" },
            function(){ return "Trinke, wenn du schon einmal Sex auf einem Esstisch hattest" },
            function(){ return "Alle trinken ihr Glas aus. Um dem zu entgehen, können sie dich auch küssen" },
            function(){ return "Lese die erste Nachricht vor, die angezeigt wird, wenn man 'Sex' in die Suchleiste eingibt" },
            function(){ return "Für eine Runde muss man sich immer die Brust streicheln, wenn man spricht" },
            function(){ return "Die anderen wählen eine Person, küsse sie auf den Mund" },
            function(){ return "Wenn du " + op() + " einen Kuss gibst, trinken alle außer euch beiden 3 Schlucke" },
            function(){ return "Mädels, ihr trinkt eure Körbchengröße in Schlucken (A = 1, B = 2, etc.)" },
            function(){ return "Du kannst ab jetzt zweimal jemanden anschauen und dabei an deinem Finger lutschen. Die andere Person trinkt" },
            function(){ return "Gib " + op() + " einen Kuss in den Nacken" },
            function(){ return "Küsse den nächesten Spieler des anderen Geschlechts " + rl() + "s von dir" },
            function(){ return "Trinke, wenn du schon einmal besoffen Sex hattest" },
            function(){ return "Alle sagen nacheinander ein Synonym für Penis. Die Person, der nichts mehr einfällt, oder etwas wiederholt, trinkt 2 Schlucke. Du beginnst" },
            function(){ return "Wähle eine Person, die ihren Kopf zwischen die Brüste einer Mitspielerin steckt" },
            function(){ return "Mache " + op() + " einen Knutschfleck oder trinkt beide 5 Schlucke" },
            function(){ return "Lass dir von einem Mitspieler deinen Arsch streicheln. Stöhne dabei erotisch" },
            function(){ return "Für oder gegen Partnertausch? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return op() + " wählt eine Person, die sich auf deinen Schoß setzt" },
            function(){ return "Wähle welcher deiner Nachbarn die Hand für eine Runde auf deinem Oberschenkel lassen muss" },
            function(){ return "Für oder gegen One-Night-Stands? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Lieber besoffener oder bekiffter Sex? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Lieber dominant oder unterwürfig? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Lieber im Kino oder im Zug rummachen? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Die Spieler rechts und links von dir müssen sich küssen" },
            function(){ return "Lieber Sex haben der unter 5 Minuten oder über einer Stunde dauert? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Denke an eine Sex-Position. Alle versucht es im Uhrzeigersinn zu erraten. Der Erste der es herausfindet darf 3 Schlucke verteilen" },
            function(){ return "Du und " + op() + " kuscheln miteinander" },
            function(){ return "Lieber einen jüngeren oder älteren Partner? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Lieber einen Partner langen oder kurzen Haaren ? Wählt alle gleichzeitig, die Minderheit trinkt" },
            function(){ return "Trinke, wenn du schon einmal erwischt wurdest, wie du es dir selbst besorgt hast" },
            function(){ return "Wenn du Lippenstift trägst, versuche auf deinem " + rl() + "en Nachbarn einen Kussabdruck zu hinterlassen" }
        ]
    }
]